Log file cannot be opened. Please check path. Trying to find:
/home/djsodano/TemoaTest/temoa/data_files/debug_logs folder
Reading data files.[    0.92]
Creating Temoa model instance.[   50.84]
Solving.Exception found in solve_temoa_instance
[Errno 2] No such file or directory: '/home/djsodano/TemoaTest/temoa/data_files/debug_logs/lp_files/tmp_d3r1w.pyomo.lp'